### ISSUE TITLE
Comma missing in panel.js

### ISSUE THREAD

**Issue by abernardgalilee** [elements-at/AlternateObjectTrees#12]
A comma is missing after the  POST.  
Ext.Ajax.request({
                url: "/admin/elements-alternate-object-trees/admin/alternate-object-tree",
                method: "POST"
                params: {
                    name: value
                },

**Comment by abernardgalilee** [comment]
Event when fixed, I now get the following : 
Timestamp: Mon Dec 30 2019 10:56:17 GMT+0100 (heure normale d’Europe centrale)
Status: 404 | Not Found
URL: /admin/elements-alternate-object-trees/admin/alternate-object-tree
Method: POST
Message: No route found for "POST /admin/elements-alternate-object-trees/admin/alternate-object-tree" (from "http://192.168.1.153/admin/")
Trace: 
in /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:136
#0 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(126): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#1 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#2 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
#3 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
#4 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#5 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(122): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#6 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /home/web-user/htdocs/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /home/web-user/htdocs/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 {main}
